### PR TITLE
Added local.wix.com to the tunnel-domains

### PR DESCRIPTION
**Pull request by gilamran**
This is the first step that we need so local.wix.com will point to localhost on SauceLabs.
The next step is to add a build step to the CI that will add local.wix.com to the hosts of the docker.

### CODE REVIEW

**Comment by shahata** [comment]
plz rebase and squash

**Comment by shahata** [comment]
regarding adding local.wix.com to hosts file. can you do this in build step? don't you need root privileges for that?

**Comment by gilamran** [comment]
I've used merge instead of rebase and I don't want to mess it all because of one line, recreated this with a new PR.

**Comment by shahata** [comment]
I sent an email once how to prevent this by configuring git to rebase by
default

**Comment by gilamran** [comment]
I did it from my home computer where I didn't have this configuration setup.

**Comment by shahata** [comment]
Well, that's your lesson for having a trash can instead of a laptop then...

**Pull request closed without merging**
