### PR TITLE
Artifact for vms

### PR DESCRIPTION
**Pull request by salickc**
Refactored Gruntfile.js to make it more maintain-friendly.
Added pom.xml patch under grunt-override.js

### CODE REVIEW

**Comment by shahata** [comment]
Looks good except for comments but two important issues:
 1. indentation seems to be bad. you use tab instead of double space?
 2. did you create this pull request from a branch that was used for a different pull request? that's going to be difficult to merge/rebase - each pull request should be from a new branch after rebasing against upstream

**Comment by salickc** [comment]
1. do you mean indentation in the modified pom.xml? I'm using pretty-data to format the xml. I can probably increase the tab size there.
2. ok, i'll fix all issues and create a new pull request.

**Comment by shahata** [comment]
I mean both xml and js. We use two spaces for each indentation level. It is just a setting you need to update in your IDE so it will use two spaces instead of tabs.

**Comment by salickc** [comment]
my js is two spaces

**Pull request closed without merging**
