### PR TITLE
Multitask hook

### PR DESCRIPTION
**Pull request by mastertheblaster**
There is a problem with multitasks which depend on the configuration.
Thus after a hook is done the configuration should be renamed too.

Tried in ShoutOut project and it worked.

However there are no tests this project so i am not still 100% sure if . replacement to _ will be bullet proof.

### CODE REVIEW

**Comment by shahata** [comment]
is there a reason not to do this in hookTask instead of creating a new method?

**Comment by mastertheblaster** [comment]
Excerpt from the official documentation: http://gruntjs.com/creating-tasks#multi-tasks
*Note that if a task has been renamed with grunt.task.renameTask, Grunt will look for a property with the new task name in the config object.*

That means that while hooking multi tasks we also need to rename the config objects.
I would like to put everything inside the hookTask. However i can't do that.
I tried looking inside the API but didn't find any property or method for checking if this is simple or multi task. Unless you have some ideas how to do that?

**Comment by shahata** [comment]
You mean that when renaming simple tasks we don't need to rename the config? Even if don't have to, why not do it anyway? After all, we are not really renaming, just duplicating

**Comment by mastertheblaster** [comment]
@shahata sorry for a long delay, but I have found out that we should not hook the multiTasks.

```javascript
grunt.registerTask('xxx', ['multi:a', 'multi:b']);
grunt.hookTask('multi').unshift('yyy');
```

The problem is that multi:a and multi:b will never be invoked.
You can close the pull request.

**Pull request closed without merging**
