### PR TITLE
feat(*): enable angular migration process

### PR DESCRIPTION
**Pull request by bolshchikov**

### CODE REVIEW

**Comment by nikaspran** [comment]
Why is this in wix-gruntfile..?

**Comment by bolshchikov** [comment]
@nikaspran, because we've added several step to the build process. We don't want every project to add those steps in their local `Gruntfile.js`. Now instead they add only a flag.

**Comment by nikaspran** [comment]
Why would wix-gruntfile even care about what version of angular we're using?

**Comment by shahata** [comment]
this code is intended to allow people to do an additional run of e2e tests with an angular version different than the one you use in bower.json. Currently the additional run uses angular 1.4.4 by default, but we will soon extend this to be a configurable array of versions. this is required by every project that needs to support multiple versions of angular. examples:
 1. common libraries that are used by multiple applications where some application uses 1.2, some 1.3, some 1.4, etc.
 2. applications comprised of multiple projects needs to gradually upgrade all of the projects to newer angular and update the angular include in their .html only after all projects support newer angular. during this migration period all projects need to support both versions.

BTW, you guys going to use this flag pretty soon in order to migrate app market to angular 1.4 :) since my-account is comprised of multiple projects, they all need to support both 1,2 and 1.4 until we finally change the include (with FT). Only after FT is merged, we can remove this flag and start using 1.4 exclusive features.

**Pull request closed without merging**
