### PR TITLE
allow overriding sauce labs related environment variables

### PR DESCRIPTION
**Pull request by GabiGrin**
I'm not sure about the name "sauceLabsConfig" as it's more of a "sauce labs environment variables override config".

### CODE REVIEW

**Comment by shahata** [comment]
Thinking about this some more, can't we just be happy with people adding this to their gruntfile:

```js
process.env.SAUCE_USERNAME = 'shahata';
process.env.SAUCE_ACCESS_KEY = 'xxx';
process.env.SAUCE_BROWSERS = 'Chrome FF';
```

:D

**Comment by GabiGrin** [comment]
Yep! even better :)

**Comment by GabiGrin** [comment]
Do you want me to add something to the readme file?

**Comment by shahata** [comment]
Yes, added. Did you verify that it works for you?

**Comment by GabiGrin** [comment]
I just needed to add /*globals process*/ to calm jshint, but other than than works like a charm.

However, security wise it might be bad to put the keys in the grunt file and they better stay in ENV.
Maybe we should only encourage changing browsers from there (which answers my first need)?

**Pull request closed without merging**
