### PR TITLE
Added new karma plugin for errors

### PR DESCRIPTION
**Pull request by guyius**
Added karma-simple-reporter plugin to the build process,
This will add new error message format to our karma unit testing. 
Phase 1 of creating more understandable test error messages.

### CODE REVIEW

**Comment by shahata** [comment]
Can you add a screen shot here with how karma report looks now?

**Comment by guyius** [comment]
Adding screen shot for few states
several failuers
single failure
success

**Comment by guyius** [comment]
@shahata 
Hey, any new regarding this PR?
Thanks.

**Comment by guyius** [comment]
@shahata 
Hey, it's been almost 2 weeks now, do you have any plans for this PR?
Thanks.

**Comment by shahata** [comment]
I tried it and it didn't work for me...
Please come over to show me how this works tomorrow and we'll merge it.
Also, please squash the commits.

**Comment by guyius** [comment]
Closing this pull request, i will create a new one.

**Pull request closed without merging**
